# Generated by Django 5.1.5 on 2025-04-25 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealfood',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_foods', to='meals.meal'),
        ),
    ]
