# Generated by Django 5.1.5 on 2025-04-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.UniqueConstraint(fields=('workout', 'exercise'), name='unique_workout_exercise'),
        ),
    ]
