# Generated by Django 5.1.5 on 2025-04-24 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workoutexercise_unique_workout_exercise'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workoutexercise',
            name='unique_workout_exercise',
        ),
    ]
