# Generated by Django 5.1.5 on 2025-04-24 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
        ('workouts', '0004_alter_workout_user_alter_workoutexercise_exercise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['-date'], 'verbose_name': 'Mashq Rejasi', 'verbose_name_plural': 'Mashq Rejalari'},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={'verbose_name': 'Mashq Parametrlari', 'verbose_name_plural': 'Mashq Parametrlari'},
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together={('user', 'date')},
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(verbose_name='Davomiylik'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='exercises.exercise', verbose_name='Mashq'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Takrorlar'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Setlar'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Og'irlik (kg)"),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout', verbose_name='Mashq Rejasi'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user', 'date'], name='workout_user_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('sets__gte', 1)), name='sets_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='workoutexercise',
            constraint=models.CheckConstraint(condition=models.Q(('reps__gte', 1)), name='reps_gte_1'),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
    ]
