# Generated by Django 5.1.5 on 2025-04-25 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_initial'),
        ('workouts', '0005_alter_workout_options_alter_workoutexercise_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workoutexercise',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='workoutexercise',
            name='sets_gte_1',
        ),
        migrations.RemoveConstraint(
            model_name='workoutexercise',
            name='reps_gte_1',
        ),
        migrations.RemoveIndex(
            model_name='workout',
            name='workout_user_date_idx',
        ),
        migrations.AlterUniqueTogether(
            name='workout',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(through='workouts.WorkoutExercise', to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='reps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='sets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.workout'),
        ),
    ]
